# Generated by Django 3.0.8 on 2020-07-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('master_pi', models.CharField(blank=True, max_length=255)),
                ('master_url', models.CharField(blank=True, max_length=255)),
                ('similar_pi', models.CharField(blank=True, max_length=255)),
                ('similar_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
